### ISSUE TITLE
Generalize from "MyEtherWallet" to "Web"

### ISSUE THREAD

**Issue by lf94** [digitalbitbox/bitbox-bridge#18]
Bity SA (specifically, myself) is going to add support for BitBox02 on our broker platform! It would be nice for people to know the bridge can be used with any website, not just MyEtherWallet. I got my BitBox02 today so the work will probably start sometime next week.

**Comment by benma** [comment]
Great to hear!

Would it suffice to add bity.com to the whitelist?

**Comment by lf94** [comment]
Ah ha, I didn't know the bridge involved a whitelist :laughing: It would almost be sufficient; we have a staging environment only accessible behind a VPN which uses bity.io as well. If you could add that for me so I can test in this environment I'd greatly appreciate it!

**Comment by benma** [comment]
> While I find it questionable to do this practice, I won't argue about it smile

What is questionable about it?

Can you clarify: do you need a certain domain to be added to the whitelist (bity.io? bity.com?) in the official release?

**Comment by lf94** [comment]
Please add bity.com to the whitelist. :slightly_smiling_face:
