### ISSUE TITLE
dev.shiftcrypto.ch – Let's Encrypt cert expired

### ISSUE THREAD

**Issue by JohannesHoppe** [digitalbitbox/bitbox-bridge#27]
<img width="485" alt="Screen Shot 2021-05-01 at 20 40 03" src="https://user-images.githubusercontent.com/640639/116791871-7695c600-aabd-11eb-8860-204731a38792.png">

**Comment by x1ddos** [comment]
This hostname is unused. Hence, we stopped reviewing the cert.

Need to update the readme.
