### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by bogorad** [digitalbitbox/bitbox-bridge#42]
I've been using the Kiwi browser for Android since it allows the use of Chrome extensions. I've successfully used various wallets. Rabby installs fine - but doesn't even suggest my BitBox02 as a valid option. Can this be implemented?

![Screenshot_20220604-192947](https://user-images.githubusercontent.com/2777398/172019344-1fdf1140-f3ba-46a2-825c-f0ba59332fe8.png)
?

**Comment by benma** [comment]
There are two potential ways to make it work:

- BitBoxBridge on on mobile
- WebHID access through Kiwi (not sure if it supports WebHID)

I am afraid either won't happen anytime soon.
