### ISSUE TITLE
Broken Linux installation on rpm

### ISSUE THREAD

**Issue by BitHighlander** [digitalbitbox/bitbox-bridge#5]
![ErrorBridge](https://user-images.githubusercontent.com/4935895/78511546-b4a9a480-775a-11ea-9b03-47c854ddb352.png)

I'm getting an error trying to install the bridge on Fedora30

**Comment by NickeZ** [comment]
Thank you for the bug report!

**Comment by NickeZ** [comment]
I've updated the release, can you please test it again? https://github.com/digitalbitbox/bitbox-bridge/releases/download/v1.1.0/bitbox-bridge-1.1.0-1.x86_64.rpm

I tested it with

```sh
sudo dnf install bitbox-bridge-1.1.0-1.x86_64.rpm
```
